##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [ ]:
import numpy as np
# Some basic arithmatic operations.
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print(f"Addition of arr1 and arr2 {arr1 + arr2}")
print(f"Subtraction of arr1 and arr2 {arr1 - arr2}")
print(f"Multiplication of arr1 and arr2 {arr1 * arr2}")
print(f"Division of arr1 and arr2 {arr1 / arr2}")

Addition of arr1 and arr2 [ 6  8 10 12]
Subtraction of arr1 and arr2 [-4 -4 -4 -4]
Multiplication of arr1 and arr2 [ 5 12 21 32]
Division of arr1 and arr2 [0.2        0.33333333 0.42857143 0.5       ]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
# Apply same operation in all the elements in array
print(arr1 * 5)
temp = arr1 * 5
temp

[ 5 10 15 20]


array([ 5, 10, 15, 20])

Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [ ]:
A = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
B = np.array([[2, 4, 1, 4], [4, 2, 4, 5]])
print(f"Addition of 2D Array : {A + B}")


Addition of 2D Array : [[3 6 4 8]
 [5 4 7 9]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [ ]:
arr = np.array([4, 8, 15, 16, 23, 42])

print(f"Sum of arr is {arr.sum()}")
print(f"Average of arr is {arr.mean()}")
print(f"Max of arr is {arr.max()}")
print(f"Min of arr is {arr.min()}")

Sum of arr is 108
Average of arr is 18.0
Max of arr is 42
Min of arr is 4


You can also do the axis based operations row-Wise and Colum-wise

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("sum : ", matrix.sum(axis = 1))
print("sum : ", matrix.sum(axis = 0))

sum :  [ 6 15 24]
sum :  [12 15 18]


In [ ]:
# sort -> on the element
arr = np.array([5, 6, 9, 1, 2, 0])
print("Element Sorting", np.sort(arr))  # sorting is imp

# argsort -> if we have to sort index first
print("This function shows the index of the element", np.argsort(arr))

Element Sorting [0 1 2 5 6 9]
This function shows the index of the element [5 3 4 0 1 2]
