In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr * 5)  # Array Broadcasting

[ 5 10 15 20 25 30 35]


##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
print(arr[[3, 5]]) # [[ we give the indexing that we have to access individually ]]

[4 6]


You can do this fancy indexing in 2D Matrix aswell

In [ ]:
# if we add one string only the hole matrix become object
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, "Chacha"]])
matrix

matrix1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(matrix1[ 2 : , 2 : ], "\n")  # This is normal slicing in numpy
# Best Method and recommended slicing

matrix2 = np.arange(1, 17).reshape(4, 4)
print(matrix2, "\n")
print(matrix2[[0, 0], [1, 2]])

[[11 12]
 [15 16]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[2 3]


##Conditional Selection
Find values based on conditions or replace them.

In [ ]:
arr = np.array([10, 2, 3, 12, 42, 23, 3, 12, 10, 34])
#Method - 1 (normal method)
# arr[arr > 15] = 0

#Method - 2 (recommended)
np.where(arr > 15, 0, arr)

array([10,  2,  3, 12,  0,  0,  3, 12, 10,  0])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [5]:
arr = np.array([9,3,5,2,6,4,1,8])
print(np.sort(arr))

[1 2 3 4 5 6 8 9]


In [6]:
print(np.argsort(arr)) # This argsort showing the indexing after sort

[6 3 1 5 2 4 7 0]


##Concatenation & Stacking

In [9]:
# Example 1: Concatenate along rows (axis=0)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.concatenate((a, b), axis = 0), "\n")

# Example 2: Concatenate along columns (axis=1)
print(np.concatenate((a, b), axis = 1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]]


Vertical & Horizontal Stacking

In [12]:
# Vertical Stacking (np.vstack())
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]


In [13]:
# Vertical Stacking (np.vstack())
print(np.hstack((a, b)))

[1 2 3 4 5 6]
