# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [4]:
pip install numpy

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [5]:
import numpy as np

In [11]:
l = [1,2,3,4,5]
arr = np.array(l)
print(arr)
print(arr)
print(arr)
print(arr)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


Lets create a matrix using list

In [14]:
l = [[1,2,3,4],[5,6,7,8]]
arr = np.array(l)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


Now lets see how matlix looks like using numpy arrays

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [16]:
arr = np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [20]:
print(np.zeros([4,4])) #[no.  of Rows, no. of Cols]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
arr = np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [23]:
arr = np.ones([2,2])
print(arr)

[[1. 1.]
 [1. 1.]]


In [58]:
arr = np.full((2,2),7)
print(arr)

[[7 7]
 [7 7]]


In [28]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [30]:
arr = np.linspace(0,2,5)
print(arr)

[0.  0.5 1.  1.5 2. ]


In [32]:
arr = np.eye(6)
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [38]:
arr = np.random.rand(3,3) #rand(rows, cols)
arr

array([[0.74664489, 0.81161345, 0.77567343],
       [0.35677617, 0.58419735, 0.18232862],
       [0.74053794, 0.83241048, 0.92941202]])

In [49]:
arr = np.random.randint(1,10,(3,3))
print(arr)

[[5 8 2]
 [3 2 9]
 [3 3 3]]


In [52]:
arr = np.random.randn(2,4)
print(arr)

#Random values that can negative also.

[[-0.04661969  0.19887693 -0.13641231 -1.33798633]
 [ 0.00618212 -0.77689666 -1.1663371   0.96370277]]


arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution