##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([[1, 2], [3, 4], [5, 6]])
print(f"Array 1 : {arr}")
print(f"Array 2 : \n{arr2}\n")

# 1. Shape -> no. of rows and columns
print(f"The shape of the array is {arr.shape}")
print(f"The shape of the array 2 is {arr2.shape}\n")

# 2. We have to check dimension of the array
print(f"The dimension of the array 1 is {arr.ndim}")
print(f"The dimension of the array 2 is {arr2.ndim}\n")

# 3. If we have to check total number of elements present in your array.
print(f"The size of array 1 is {arr.size}")
print(f"The size of array 2 is {arr2.size}\n")

# 4. To check the data type
print(f"The type of the array 1 is {arr.dtype}")
print(f"The type of the array 2 is {arr2.dtype}\n")



Array 1 : [1 2 3 4 5 6 7]
Array 2 : 
[[1 2]
 [3 4]
 [5 6]]

The shape of the array is (7,)
The shape of the array 2 is (3, 2)

The dimension of the array 1 is 1
The dimension of the array 2 is 2

The size of array 1 is 7
The size of array 2 is 6

The type of the array 1 is int64
The type of the array 2 is int64



##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
print(arr[1])

2


In [ ]:
# Slicing = (start, stop, step)
print(arr[1 : 4])
print(arr)

[2 3 4]
[1 2 3 4 5 6 7]


Now lets see the 2D indexing aswell

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# matrix[row_index, col_index]
print(matrix, "\n")
print(matrix[2, 2])
print(matrix[0, 2])
print(matrix[2, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

9
3
7


Now we can also do the slicing lets see the **slicing in 1D**

In [3]:
arrr = [10, 20, 30, 40, 50, 60]
print(arrr[1 : 4])

[20, 30, 40]


1D slicing was really easy now lets see the **slicing in 2D**

In [ ]:
print(matrix, "\n")

print("2D Matrix Slicing")
# matrix[row_start_index : row_stop_index , col_start_index : col_stop_index]
print(matrix[0:2, 0:2],"\n")

# print(matrix[1:3 , 1:3])
print(matrix[1: , 1: ], "\n")


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

2D Matrix Slicing
[[1 2]
 [4 5]] 

[[5 6]
 [8 9]] 



There is one more thing known as **Boolean indexing**

In [ ]:
arr3 = np.array([5, 10, 15, 18, 20, 22])
print(arr3 < 18, "\n")

print(arr3[arr3 < 18])

[ True  True  True False False False] 

[ 5 10 15]


## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [ ]:
import numpy as np
arr = np.arange(1, 13)
print(arr.reshape(4, 3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix, "\n")
print(matrix.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9]
