In [1]:
import numpy as np

# NumPy Practice Questions - Set 2

Intermediate-level practice. No solutions included.

## Question 1

Create a 6×6 array containing numbers from 1 to 36.


In [2]:
# Write your code here
arr = np.arange(1, 37).reshape(6, 6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


## Question 2

Extract the first row, last row, first column, last column, and main diagonal.


In [3]:
# Write your code here
print("First Row:", arr[0], '\n')
print("Last Row:", arr[-1], '\n')
print("First Column:", arr[ : , 0], '\n')
print("Last Column:", arr[ : , -1], '\n')
print("Diagonal:", np.diag(arr))

First Row: [1 2 3 4 5 6] 

Last Row: [31 32 33 34 35 36] 

First Column: [ 1  7 13 19 25 31] 

Last Column: [ 6 12 18 24 30 36] 

Diagonal: [ 1  8 15 22 29 36]


## Question 3

Extract all even numbers using Boolean indexing.


In [4]:
# Write your code here
print(arr % 2 == 0)

[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]


## Question 4

Replace every element divisible by 3 with -1 without using loops.


In [5]:
# Write your code here
arr[arr % 3 == 0] = -1
print(arr)

[[ 1  2 -1  4  5 -1]
 [ 7  8 -1 10 11 -1]
 [13 14 -1 16 17 -1]
 [19 20 -1 22 23 -1]
 [25 26 -1 28 29 -1]
 [31 32 -1 34 35 -1]]


## Question 5

Create two random (4×4) arrays and compare them using >, <, ==, and !=.


In [6]:
# Write your code here
arr1 = np.random.randint(1, 101, size = 16).reshape(4, 4)
arr2 = np.random.randint(1, 101, size = 16).reshape(4, 4)
print(arr1 < arr2, '\n')
print(arr1 > arr2, '\n')
print(arr1 == arr2, '\n')
print(arr1 != arr2)

[[ True  True False False]
 [False False  True False]
 [ True False  True  True]
 [ True  True False False]] 

[[False False  True  True]
 [ True  True False  True]
 [False  True False False]
 [False False  True  True]] 

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]] 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## Question 6

Find the indices of all elements greater than the mean of an array.


In [7]:
# Write your code here
arr1 = np.array([4, 5, 10, 48, 41, 11, 3, 7, 32, 20])
print("Mean:", arr1.mean(),  "Or",  np.mean(arr1))
indices = np.where(arr1 > arr1.mean())[0]
print(indices)

Mean: 18.1 Or 18.1
[3 4 8 9]


## Question 7

Use `np.where()` to replace values greater than 50 with 100, otherwise 0.


In [8]:
# Write your code here
arr2 = np.random.randint(30, 70, size = 36).reshape(6, 6)
print(np.where(arr2 > 50, 100, 0))
print(np.where(arr2 > 50))

[[100   0   0   0 100 100]
 [100 100 100 100   0 100]
 [  0   0 100   0 100   0]
 [  0 100   0   0 100   0]
 [100 100 100   0 100 100]
 [100 100 100 100 100   0]]
(array([0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5]), array([0, 4, 5, 0, 1, 2, 3, 5, 2, 4, 1, 4, 0, 1, 2, 4, 5, 0, 1, 2, 3, 4]))


## Question 8

Generate 20 equally spaced values between 5 and 100 using `linspace()`.


In [9]:
# Write your code here
arr = np.linspace(5, 100, 20)
print(arr)

[  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.  70.
  75.  80.  85.  90.  95. 100.]


## Question 9

Concatenate two 3×3 arrays vertically and horizontally.


In [10]:
# Write your code here
arr1 = np.arange(9).reshape(3, 3)
arr2 = np.arange(10, 19).reshape(3, 3)
print(np.concatenate((arr1, arr2), axis = 0), '\n')
print(np.concatenate((arr1, arr2), axis = 1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]


## Question 10

Split a 6×6 array into three equal parts row-wise and column-wise.



In [11]:
arr = np.arange(36).reshape(6, 6)
print(arr, '\n')
print(np.vsplit(arr, 3), '\n')
print(np.hsplit(arr, 3))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]] 

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])] 

[array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25],
       [30, 31]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27],
       [32, 33]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23],
       [28, 29],
       [34, 35]])]


## Question 11

Find all unique values and their frequencies.


In [12]:
# Write your code here
arr = np.random.randint(1, 10, size = 20).reshape(5, 4)
unique, count = np.unique(arr, return_counts = True)
print("Unique value with frequencies")
print(unique)
print(count)

Unique value with frequencies
[1 2 3 4 6 7 8 9]
[2 2 4 3 1 2 4 2]


## Question 12

Normalize a 5×5 random matrix so all values lie between 0 and 1.


In [13]:
# Write your code here
arr = np.random.randint(0, 2, size=(5, 5))
print(arr)

[[0 0 1 1 1]
 [0 1 1 0 1]
 [1 0 1 1 0]
 [1 0 1 1 1]
 [0 0 1 1 1]]


## Question 13

Calculate cumulative sum (`cumsum`) and cumulative product (`cumprod`).


In [14]:
# Write your code here
arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr)
print("Cumulative Sum:", np.cumsum(arr))
print("Cumulative Product:", np.cumprod(arr))

Array: [1 2 3 4 5]
Cumulative Sum: [ 1  3  6 10 15]
Cumulative Product: [  1   2   6  24 120]


## Question 14

Find the transpose of a matrix and verify the new shape.


In [15]:
# Write your code here
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Matrix:")
print(arr, '\n')

print("Transpose:")
print(arr.T)

Original Matrix:
[[1 2 3]
 [4 5 6]] 

Transpose:
[[1 4]
 [2 5]
 [3 6]]


## Question 15

From a 5×5 matrix, extract the four corners, all border elements, and the center element.


In [16]:
# Write your code here
arr = np.random.randint(1, 26, size=(5, 5))
# arr = np.random.randint(1, 26, size = 25).reshape(5, 5)
print(arr, '\n')

print(arr[0, 0])
print(arr[0, -1])
print(arr[-1, 0])
print(arr[-1, -1], '\n')

print(arr[0])
print(arr[ : , -1])
print(arr[ -1, :])
print(arr[ : , 0], '\n')

print(arr[2, 2])

[[24  3 24  1 25]
 [25  9 10  7 23]
 [16 22 19  9 10]
 [24  1 22  3 25]
 [ 9  2 25 12 12]] 

24
25
9
12 

[24  3 24  1 25]
[25 23 10 25 12]
[ 9  2 25 12 12]
[24 25 16 24  9] 

19
