# 📝 NumPy Assignment – Class 3

### Instructions
- Import NumPy as `np`.
- Solve each question in the code cell below it.
- Print the output wherever required.

## Q1. Import NumPy as `np`.

In [4]:
# Write your code here
import numpy as np

## Q2. Create a NumPy array: `[10, 20, 30, 40, 50]`.

In [9]:
# Write your code here
arr = np.arange(10, 51, 10)
print(arr)

[10 20 30 40 50]


## Q3. Add `5` to every element of the above array.

In [10]:
# Write your code here
print(arr + 5)

[15 25 35 45 55]


## Q4. Multiply every element by `2`.

In [11]:
# Write your code here
print(arr * 2)

[ 20  40  60  80 100]


## Q5. Create the following 3×3 array:
```
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

In [13]:
# Write your code here
arr2 = np.arange(1, 10).reshape(3, 3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Q6. Add `10` to every element of the above array.

In [16]:
# Write your code here
print(arr2 + 10)

arr3 = arr2.copy()

[[11 12 13]
 [14 15 16]
 [17 18 19]]


## Q7. Multiply every element of the above array by `3`.

In [18]:
# Write your code here
print(arr3 * 3)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


## Q8. Create `arr = np.array([1,2,3])` and add it to:
```
[[10,20,30],
 [40,50,60]]
```

In [20]:
# Write your code here
arr4 = np.array([1,2,3])
arr5 = np.array([[10,20,30], [40,50,60]])
print(arr4 + arr5)

[[11 22 33]
 [41 52 63]]


## Q9. Create `arr = np.array([5,10,15,20,25])` and find its **sum**.

In [23]:
# Write your code here
arr6 = np.array([5,10,15,20,25])
print(arr6.sum())

75


## Q10. Find the **mean** of the above array.

In [24]:
# Write your code here
print(np.mean(arr6))

15.0


## Q11. Find the **maximum** and **minimum** value.

In [27]:
# Write your code here
print("Maximun: ", np.max(arr6))
print("Minimum: ", np.min(arr6))

Maximun:  25
Minimum:  5


## Q12. Find the **standard deviation**.

In [28]:
# Write your code here
print(np.std(arr6))

7.0710678118654755


## Q13. Create:
```
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
```

In [32]:
# Write your code here
arr7 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr7


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Q14. Find the **row-wise sum** (`axis=1`).

In [35]:
# Write your code here
print(np.sum(arr7, axis = 1))

[ 60 150 240]


## Q15. Find the **column-wise sum** (`axis=0`).

In [36]:
# Write your code here
print(np.sum(arr7, axis = 0))

[120 150 180]
