In [1]:
import numpy as np

# NumPy Practice Questions - Set 1

These questions are for practice only. Do **not** include solutions. Complete these before requesting the next set.

## Question 1

Create a 1D NumPy array containing numbers from 1 to 20.


In [2]:
# Write your code here
arr = np.arange(1, 21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## Question 2

Create a 5×5 array filled with zeros and another filled with ones.


In [3]:
# Write your code here
arr1 = np.zeros((5, 5))
print(arr1, "\n")

arr2 = np.ones((5, 5))
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Question 3

Create a 4×4 identity matrix.



In [4]:
# Write your code here
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Question 4

Generate an array of even numbers from 10 to 100.


In [5]:
# Write your code here
arr = np.arange(10, 101, 10)
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


## Question 5

Create an array of 15 random integers between 1 and 100.


In [6]:
# Write your code here
arr = np.random.randint(1, 101, size = 15)
print(arr)

[80 95 11 19 82 17 86 22  5 74 39 20 22 15 69]


## Question 6

Find the shape, size, number of dimensions, and data type of a given array.


In [7]:
# Write your code here
arr = np.arange(12).reshape(3, 4)
print(arr, '\n')
print("Shape:", arr.shape, '\n')
print("Size:", arr.size, '\n')
print("Data Type:", arr.dtype, '\n')
print("Dimention:", arr.ndim, '\n')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Shape: (3, 4) 

Size: 12 

Data Type: int64 

Dimention: 2 



## Question 7

Reshape a 1D array of 24 elements into a 4×6 matrix.


In [8]:
# Write your code here
arr = np.arange(24)
print(arr, '\n')
ndim_arr = arr.reshape(4, 6)
print(ndim_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## Question 8

Flatten a 3×3 matrix using both `flatten()` and `ravel()`.


In [9]:
# Write your code here
arr = np.full((3, 3), 7)
print(arr, '\n')
convert_1d = arr.flatten()
print(convert_1d)

[[7 7 7]
 [7 7 7]
 [7 7 7]] 

[7 7 7 7 7 7 7 7 7]


## Question 9

Extract all elements greater than 50 from a random integer array.


In [10]:
# Write your code here
arr = np.random.randint(30, 80, size = 16).reshape(4, 4)
print(arr, '\n')
print(arr[arr > 50])

[[66 65 42 60]
 [57 72 68 32]
 [58 64 54 64]
 [69 42 34 71]] 

[66 65 60 57 72 68 58 64 54 64 69 71]


## Question 10

Replace all negative values in an array with 0.


In [11]:
# Write your code here
arr = np.arange(-5, 11)
print(arr, '\n')
arr[arr < 0] = 0
print(arr)

[-5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10] 

[ 0  0  0  0  0  0  1  2  3  4  5  6  7  8  9 10]


## Question 11

Create two 3×3 matrices and perform addition, subtraction, multiplication (element-wise), and matrix multiplication.


In [12]:
# Write your code here
arr1 = np.random.randint(1, 50, size = 9).reshape(3, 3)
arr2 = np.random.randint(1, 50, size = 9).reshape(3, 3)
print(arr1 + arr2, '\n')
print(arr1 - arr2, '\n')
print(arr1 * 7, '\n')
print(arr1 * arr2, '\n')
print((arr1 / arr2).astype(int))

[[52 19 55]
 [74 17 56]
 [46 54 56]] 

[[-28   3 -21]
 [-12   1  -4]
 [ 34  38   8]] 

[[ 84  77 119]
 [217  63 182]
 [280 322 224]] 

[[ 480   88  646]
 [1333   72  780]
 [ 240  368  768]] 

[[0 1 0]
 [0 1 0]
 [6 5 1]]


## Question 12

Find the maximum, minimum, mean, median, standard deviation, and sum of an array.


In [13]:
# Write your code here
arr = np.arange(1, 17)
print(arr, '\n')
print("Maximum:", np.max(arr), '\n')
print("Minimun:", np.min(arr), '\n')
print("Mean:", np.mean(arr), '\n')
print("Standard deviation:", np.std(arr), '\n')
print("Sum of array:", np.sum(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] 

Maximum: 16 

Minimun: 1 

Mean: 8.5 

Standard deviation: 4.6097722286464435 

Sum of array: 136


## Question 13

Sort a NumPy array in ascending order and then reverse it into descending order.


In [14]:
# Write your code here
arr = np.random.randint(1, 11, size = 5)
print(np.sort(arr))

[2 4 5 6 8]


## Question 14

Using fancy indexing, extract the 1st, 3rd, 5th, and 7th elements from a 1D array.


In [15]:
# Write your code here
arr = np.arange(20, 31)
print(arr[[1, 3, 5, 7]])

[21 23 25 27]


## Question 15

Given a 5×5 matrix, extract the middle 3×3 submatrix using slicing.



In [16]:
# Write your code here
arr = np.arange(25).reshape(5, 5)
print(arr, '\n')
print(arr[ 1:4 , 1:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]
