
# NumPy Assignment — Array Attributes, Indexing & Slicing



# Q1. Array Attributes

## Problem Statement
Create the following NumPy array:

```python
[10, 20, 30, 40, 50]
```

Print:
- Shape
- Number of Dimensions
- Size
- Data Type

## Sample Output
```python
Shape: (5,)
Dimensions: 1
Size: 5
dtype: int64
```


In [8]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print("Shape: ", arr.shape)
print("Number of Dimentions: ", arr.ndim)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)

[10 20 30 40 50]
Shape:  (5,)
Number of Dimentions:  1
Size:  5
Data Type:  int64



# Q2. Find Array Shape

## Problem Statement
Create the following array:

```python
[[1,2,3],
 [4,5,6]]
```

Print only the shape of the array.

## Sample Output
```python
(2, 3)
```


In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape)

(2, 3)



# Q3. 1D Indexing

## Problem Statement
Create the array:

```python
[5, 10, 15, 20, 25]
```

Print:
- First element
- Last element

## Sample Output
```python
5
25
```


In [10]:
arr3 = np.array([5, 10, 15, 20, 25])
print(arr3[:1])
print(arr3[-1:])

[5]
[25]



# Q4. 2D Indexing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the element `50`.

## Sample Output
```python
50
```


In [14]:
arr4 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr4, "\n")
print(arr4[1, 1])

[[10 20 30]
 [40 50 60]
 [70 80 90]] 

50



# Q5. 2D Indexing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the element `9`.

## Sample Output
```python
9
```


In [15]:
arr5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr5[2,2])

9



# Q6. 1D Slicing

## Problem Statement
Create the array:

```python
[10,20,30,40,50,60]
```

Print elements from index 1 to 4.

## Sample Output
```python
[20 30 40 50]
```


In [16]:
arr6 = np.array([10, 20, 30, 40, 50, 60])
print(arr6[1 : 4])

[20 30 40]



# Q7. 1D Slicing

## Problem Statement
Create the array:

```python
[1,2,3,4,5,6,7,8]
```

Print the first 5 elements.

## Sample Output
```python
[1 2 3 4 5]
```


In [18]:
arr7 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr7[:5])

[1 2 3 4 5]



# Q8. 2D Slicing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the first two rows.

## Sample Output
```python
[[1 2 3]
 [4 5 6]]
```


In [21]:
arr8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sliced = arr8[0:2 , 0:]    # slicing rule [Row index , col index]
print(sliced)

[[1 2 3]
 [4 5 6]]



# Q9. 2D Slicing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the first two columns of all rows.

## Sample Output
```python
[[10 20]
 [40 50]
 [70 80]]
```


In [22]:
arr9 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr9[ : , : 2])

[[10 20]
 [40 50]
 [70 80]]


# Q10. `np.eye()`

## Problem Statement
Using NumPy, create a **4 × 4 identity matrix** using the `np.eye()` function.

Print the resulting matrix.

## Sample Output
```python
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
```

In [24]:
arr10 = np.eye(4)
print(arr10)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Boolean Indexing (Practice)

**Q1.** Create a NumPy array from 1 to 20. Print only the elements greater than 10 using boolean indexing.



In [28]:
# arra1 = np.array([i for i in range(1, 21)])
arra1 = np.arange(1, 21)
print(arra1 > 10)


[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True]



**Q2.** Create the array:
```python
arr = np.array([12, 5, 18, 7, 25, 30, 2, 15])
```
Print only the even numbers using boolean indexing.


In [29]:
arra2 = np.array([12, 5, 18, 7, 25, 30, 2, 15])
print(arra2)
print(arra2 % 2 == 0)

[12  5 18  7 25 30  2 15]
[ True False  True False False  True  True False]



**Q3.** Create a 4×4 random integer array (1–50). Print only the values greater than 25 using boolean indexing.


In [32]:
arra4 = np.random.randint(1, 51, size = (4, 4))
print(arra4, "\n")
print(arra4 > 25)

[[ 5 14 12 22]
 [20 45 43 19]
 [50 30 43 17]
 [ 4 16 30 15]] 

[[False False False False]
 [False  True  True False]
 [ True  True  True False]
 [False False  True False]]
